# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tinyPlant',
                'doc_host': 'https://yukontaf.github.io',
                'git_url': 'https://github.com/yukontaf/tinyPlant',
                'lib_path': 'tinyPlant'},
  'syms': {'tinyPlant.core': {'tinyPlant.core.foo': ('core.html#foo', 'tinyPlant/core.py')}}}
